//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FichaTecnicaServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FichaTecnicaEntities : DbContext
    {
        public FichaTecnicaEntities()
            : base("name=FichaTecnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalisisServer> AnalisisServer { get; set; }
        public virtual DbSet<CarpetasCompartidas> CarpetasCompartidas { get; set; }
        public virtual DbSet<Datos_de_la_red> Datos_de_la_red { get; set; }
        public virtual DbSet<DatosTecnicos> DatosTecnicos { get; set; }
        public virtual DbSet<DB> DB { get; set; }
        public virtual DbSet<Particiones> Particiones { get; set; }
        public virtual DbSet<Software_instalado> Software_instalado { get; set; }
        public virtual DbSet<Updates> Updates { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<RespaldosDB> RespaldosDB { get; set; }
    }
}
